### ISSUE TITLE
Replace rand when choosing which bot to play

### ISSUE THREAD

**Issue by Thomas1995** [Thomas1995/Rentz#12]
@ericpts @bicsi

We should replace the rand() when a client chooses a bot to play.

We have two options:
1. Client takes the number of a bot (int) or the name of a bot (string) as parameter.
2. Keep something on the server that indicates the next bot available and sends to the client a bot that was not chosen yet. If the number of clients is greater then the number of bots, then we can repeat them, but it should be at least one bot of each kind.

I would prefer the second one, because like this we can have less parameters for the clients.

It would be interesting if we would implement both.

**Comment by Thomas1995** [comment]
Option 1 was implemented in https://github.com/Thomas1995/Rentz/commit/94f38190ecf52e2a797b9de49928db45dee22f38

**Comment by bicsi** [comment]
Solved. Lock the issue.
