### ISSUE TITLE
localhost parameter for client

### ISSUE THREAD

**Issue by Thomas1995** [Thomas1995/Rentz#13]
@ericpts @bicsi 

I think client takes too much parameters, so we should remove the "localhost" one which is always the same. What do you say?

**Comment by ericpts** [comment]
The idea is that we can host the server on one computer and clients from everywhere can connect.

It is not meant to be purely local.

**Comment by Thomas1995** [comment]
Yes, but we can make it a default parameter. If you do not type localhost, the default option will be localhost.

**Comment by bicsi** [comment]
I would say we should leave it there. It would be harder to implement an args parser with optional arguments. And, as eric said, being able to host it through a network is a plus

**Comment by ericpts** [comment]
Solved by 220e12de
