### ISSUE TITLE
Make server reject incoming connections (or put in waiting queue) while game is playing -- now it gives SegFault

### ISSUE THREAD

**Issue by bicsi** [Thomas1995/Rentz#21]

**Comment by Thomas1995** [comment]
I tried to solve it in https://github.com/Thomas1995/Rentz/commit/7a6541f601c1886dac49dc1dfcb023baaa5b8969. Try it now.

**Comment by Thomas1995** [comment]
I've done some testing. Apparently, the problem you found does not occur in the circumstances described in this issue. Please try to recreate it and post another issue with the steps leading to this bug.
